### ISSUE TITLE
Lots of warning

### ISSUE THREAD

**Issue by tlenclos** [redirectionio/vercel-middleware#1]
I got a lot of these logs while using this middleware

```
%cWARN%c libredirectionio/src/api/log.rs:91%c cannot parse ip address , skipping color: white; padding: 0 3px; background: orange; font-weight: bold; color: inherit background: inherit; color: inherit
This method will be removed in the next major version. Use `import { ipAddress } from @vercel/functions` instead.
```

Is there a way I could suppress them ?

**Comment by markomitranic** [comment]
Deal @joelwurtz this has already been reported but here is a visualization to help raise urgency...
Not only will we be blocked from upgrading to Next 15, which is said to be released next month, but also, my logs look like this. Its quite unfortunate. And costs money on the log drain side.

When can we expect some sort of a fix for this?

<img width="947" alt="Screenshot 2024-09-06 at 02 23 22" src="https://github.com/user-attachments/assets/75b32648-bf67-4fb2-9141-64fdc569bb84">

**Comment by joelwurtz** [comment]
Last versions should fix thoses issues, please tell use if you still have a lot of logs
